#include <stdint.h>

// Modifier Keys
#define LEFT_CTRL       1<<0
#define LEFT_SHIFT      1<<1
#define LEFT_ALT        1<<2
#define LEFT_GUI        1<<3
#define RIGHT_CTRL      1<<4
#define RIGHT_SHIFT     1<<5
#define RIGHT_ALT       1<<6
#define RIGHT_GUI       1<<7

//Keyboard mapping
//Refer: https://www.usb.org/sites/default/files/hut1_3_0.pdf
#define KEY_RESERVED_00              0x00
#define KEY_ERROR_ROLL_OVER          0x01
#define KEY_POST_FAIL                0x02
#define KEY_ERROR_UNDEFINED          0x03
#define KEY_A                        0x04
#define KEY_B                        0x05
#define KEY_C                        0x06
#define KEY_D                        0x07
#define KEY_E                        0x08
#define KEY_F                        0x09
#define KEY_G                        0x0A
#define KEY_H                        0x0B
#define KEY_I                        0x0C
#define KEY_J                        0x0D
#define KEY_K                        0x0E
#define KEY_L                        0x0F
#define KEY_M                        0x10
#define KEY_N                        0x11
#define KEY_O                        0x12
#define KEY_P                        0x13
#define KEY_Q                        0x14
#define KEY_R                        0x15
#define KEY_S                        0x16
#define KEY_T                        0x17
#define KEY_U                        0x18
#define KEY_V                        0x19
#define KEY_W                        0x1A
#define KEY_X                        0x1B
#define KEY_Y                        0x1C
#define KEY_Z                        0x1D
#define KEY_1                        0x1E
#define KEY_2                        0x1F
#define KEY_3                        0x20
#define KEY_4                        0x21
#define KEY_5                        0x22
#define KEY_6                        0x23
#define KEY_7                        0x24
#define KEY_8                        0x25
#define KEY_9                        0x26
#define KEY_0                        0x27
#define KEY_ENTER                    0x28
#define KEY_ESCAPE                   0x29
#define KEY_BACKSPACE                0x2A
#define KEY_TAB                      0x2B
#define KEY_SPACEBAR                 0x2C
#define KEY_MINUS                    0x2D
#define KEY_EQUAL                    0x2E
#define KEY_OPEN_SQUARE_BRACKET      0x2F
#define KEY_CLOSE_SQUARE_BRACKET     0x30
#define KEY_BACKSLASH                0x31
#define KEY_NONUS_TILDE              0x32
#define KEY_SEMICOLON                0x33
#define KEY_APOSTROPHE               0x34
#define KEY_GRAVE                    0x35
#define KEY_COMMA                    0x36
#define KEY_PERIOD                   0x37
#define KEY_FOWARDSLASH              0x38
#define KEY_CAPSLOCK                 0x39
#define KEY_F1                       0x3A
#define KEY_F2                       0x3B
#define KEY_F3                       0x3C
#define KEY_F4                       0x3D
#define KEY_F5                       0x3E
#define KEY_F6                       0x3F
#define KEY_F7                       0x40
#define KEY_F8                       0x41
#define KEY_F9                       0x42
#define KEY_F10                      0x43
#define KEY_F11                      0x44
#define KEY_F12                      0x45
#define KEY_PRINTSCREEN              0x46
#define KEY_SCROOLLOCK               0x47
#define KEY_PAUSE                    0x48
#define KEY_INSERT                   0x49
#define KEY_HOME                     0x4A
#define KEY_PAGE_UP                  0x4B
#define KEY_DELETE                   0x4C
#define KEY_END                      0x4D
#define KEY_PAGE_DOWN                0x4E
#define KEY_RIGHT_ARROW              0x4F
#define KEY_LEFT_ARROW               0x50
#define KEY_DOWN_ARROW               0x51
#define KEY_UP_ARROW                 0x52
#define KEY_NUMLOCK                  0x53
#define KEY_PAD_FORWARD_SLASH        0x54
#define KEY_PAD_ASTERISK             0x55
#define KEY_PAD_MINUS                0x56
#define KEY_PAD_PLUS                 0x57
#define KEY_PAD_ENTER                0x58
#define KEY_PAD_1                    0x59
#define KEY_PAD_2                    0x5A
#define KEY_PAD_3                    0x5B
#define KEY_PAD_4                    0x5C
#define KEY_PAD_5                    0x5D
#define KEY_PAD_6                    0x5E
#define KEY_PAD_7                    0x5F
#define KEY_PAD_8                    0x60
#define KEY_PAD_9                    0x61
#define KEY_PAD_0                    0x62
#define KEY_PAD_PERIOD               0x63
#define KEY_NONUS_BACKSLASH          0x64
#define KEY_APPLICATION              0x65
#define KEY_POWER                    0x66
#define KEY_PAD_EQUAL                0x67
#define KEY_F13                      0x68
#define KEY_F14                      0x69
#define KEY_F15                      0x6A
#define KEY_F16                      0x6B
#define KEY_F17                      0x6C
#define KEY_F18                      0x6D
#define KEY_F19                      0x6E
#define KEY_F20                      0x6F
#define KEY_F21                      0x70
#define KEY_F22                      0x71
#define KEY_F23                      0x72
#define KEY_F24                      0x73
#define KEY_EXECUTE                  0x74
#define KEY_HELP                     0x75
#define KEY_MENU                     0x76
#define KEY_SELECT                   0x77
#define KEY_STOP                     0x78
#define KEY_AGAIN                    0x79
#define KEY_UNDO                     0x7A
#define KEY_CUT                      0x7B
#define KEY_COPY                     0x7C
#define KEY_PASTE                    0x7D
#define KEY_FIND                     0x7E
#define KEY_MUTE                     0x7F
#define KEY_VOL_UP                   0x80
#define KEY_VOL_DOWN                 0x81
#define KEY_LOCKING_CAPSLOCK         0x82
#define KEY_LOCKING_NUMLOCK          0x83
#define KEY_LOCKING_SCROLLLOCK       0x84
#define KEY_PAD_COMMA                0x85
#define KEY_PAD_EQUAL_2              0x86
#define KEY_INTERNATION_1            0x87
#define KEY_INTERNATION_2            0x88
#define KEY_INTERNATION_3            0x89
#define KEY_INTERNATION_4            0x8A
#define KEY_INTERNATION_5            0x8B
#define KEY_INTERNATION_6            0x8C
#define KEY_INTERNATION_7            0x8D
#define KEY_INTERNATION_8            0x8E
#define KEY_INTERNATION_9            0x8F
#define KEY_LANG_1                   0x90
#define KEY_LANG_2                   0x91
#define KEY_LANG_3                   0x92
#define KEY_LANG_4                   0x93
#define KEY_LANG_5                   0x94
#define KEY_LANG_6                   0x95
#define KEY_LANG_7                   0x96
#define KEY_LANG_8                   0x97
#define KEY_LANG_9                   0x98
#define KEY_ALTERNATE_ERASE          0x99
#define KEY_SYSRQ                    0x9A
#define KEY_CANCEL                   0x9B
#define KEY_CLEAR                    0x9C
#define KEY_PRIOR                    0x9D
#define KEY_RETURN                   0x9E
#define KEY_SEPERATOR                0x9F
#define KEY_OUT                      0xA0
#define KEY_OPER                     0xA1
#define KEY_CLEAR_AGAIN              0xA2
#define KEY_CRSEL                    0xA3
#define KEY_EXCEL                    0xA4
#define KEY_RESERVED_A5              0xA5
#define KEY_RESERVED_A6              0xA6
#define KEY_RESERVED_A7              0xA7
#define KEY_RESERVED_A8              0xA8
#define KEY_RESERVED_A9              0xA9
#define KEY_RESERVED_AA              0xAA
#define KEY_RESERVED_AB              0xAB
#define KEY_RESERVED_AC              0xAC
#define KEY_RESERVED_AD              0xAD
#define KEY_RESERVED_AE              0xAE
#define KEY_RESERVED_AF              0xAF
#define KEY_PAD_00                   0xB0
#define KEY_PAD_000                  0xB1
#define KEY_THOUSAND_SEPARATOR       0xB2
#define KEY_DECIMAL_SEPARATOR        0xB3
#define KEY_CURRENCY_UNIT            0xB4
#define KEY_CURRENCY_SUB_UNIT        0xB5
#define KEY_PAD_OPEN_BRACKET         0xB6
#define KEY_PAD_CLOSE_BRACKET        0xB7
#define KEY_PAD_OPEN_CURLY_BRACKET   0xB8
#define KEY_PAD_CLOSE_CURLY_BRACKET  0xB9
#define KEY_PAD_TAB                  0xBA
#define KEY_PAD_BACKSPACE            0xBB
#define KEY_PAD_A                    0xBC
#define KEY_PAD_B                    0xBD
#define KEY_PAD_C                    0xBE
#define KEY_PAD_D                    0xBF
#define KEY_PAD_E                    0xC0
#define KEY_PAD_F                    0xC1
#define KEY_PAD_XOR                  0xC2
#define KEY_PAD_CARET                0xC3
#define KEY_PAD_PERCENTAGE           0xC4
#define KEY_PAD_OPEN_ANGLE_BRACKET   0xC5
#define KEY_PAD_CLOSE_ANGLE_BRACKET  0xC6
#define KEY_PAD_AMPERSAND            0xC7
#define KEY_PAD_DOUBLE_AMPERSAND     0xC8
#define KEY_PAD_VERTICAL_BAR         0xC9
#define KEY_PAD_DOUBLE_VERTICAL_BAR  0xCA
#define KEY_PAD_COLON                0xCB
#define KEY_PAD_HASH                 0xCC
#define KEY_PAD_SPACE                0xCD
#define KEY_PAD_AT                   0xCE
#define KEY_PAD_EXCLAMATION          0xCF
#define KEY_PAD_MEMORY_STORE         0xD0
#define KEY_PAD_MEMORY_RECALL        0xD1
#define KEY_PAD_MEMORY_CLEAR         0xD2
#define KEY_PAD_MEMORY_ADD           0xD3
#define KEY_PAD_MEMORY_SUBTRACT      0xD4
#define KEY_PAD_MEMORY_MULTIPLY      0xD5
#define KEY_PAD_MEMORY_DIVIDE        0xD6
#define KEY_PAD_PLUS_MINUS           0xD7
#define KEY_PAD_CLEAR                0xD8
#define KEY_PAD_CLEAR_ENTER          0xD9
#define KEY_PAD_BINARY               0xDA
#define KEY_PAD_OCTAL                0xDB
#define KEY_PAD_DECIMAL              0xDC
#define KEY_PAD_HEXADECIMAL          0xDD
#define KEY_RESERVED_DE              0xDE
#define KEY_RESERVED_DF              0xDF
#define KEY_LEFT_CTRL                0xE0
#define KEY_LEFT_SHIFT               0xE1
#define KEY_LEFT_ALT                 0xE2
#define KEY_LEFT_GUI                 0xE3
#define KEY_RIGHT_CTRL               0xE4
#define KEY_RIGHT_SHIFT              0xE5
#define KEY_RIGHT_ALT                0xE6
#define KEY_RIGHT_GUI                0xE7

struct {
    uint8_t modifier_key;
    uint8_t reserved;
    uint8_t keys[6];
} keyboard_packet;